### ISSUE TITLE
Traceback when running GCS on a Linux environment

### ISSUE THREAD

**Issue by juangallostra** [simondlevy/Hackflight#24]
When trying to start the GCS in a Linux environment the following Traceback is raised:
```python
Traceback (most recent call last):
  File "hackflight.py", line 499, in <module>
    gcs = GCS()
  File "hackflight.py", line 133, in __init__
    self.attitude_request = msppg.serialize_GET_ATTITUDE_RADIANS_Request()
AttributeError: 'module' object has no attribute 'serialize_GET_ATTITUDE_RADIANS_Request'
```
I think that changes made in d7eaa56afe21c2434a9532f051eb19724e6b2ea4 may be the culprit.

**Comment by juangallostra** [comment]
True, I forgot I had to re-run `msppg.py`! :see_no_evil:

**Comment by juangallostra** [comment]
Re-ran the commands and issue is solved. GCS working again! Closing the issue.
